services:
  be-function:
    build:
      context: ./
      dockerfile: Dockerfile-be-function-src
    container_name: "${DOCKER_NAME}-be-function"
    ports:
      - "${BE_FUNCTION_PORT}:5000"
    env_file:
      - .env
    environment:
      BASE_URL: "http://localhost:${BE_FUNCTION_PORT}"
      DYNAMODB_ENDPOINT: "http://${DOCKER_NAME}-dynamodb:8000"
    volumes:
      - ./be-function-src:/app
      - ./.env:/.env
    networks:
      - network

  dynamodb:
    image: amazon/dynamodb-local
    container_name: "${DOCKER_NAME}-dynamodb"
    ports:
      - "${DYNAMODB_PORT}:8000"
    networks:
      - network

  scripts:
    build:
      context: ./scripts
      dockerfile: Dockerfile
    container_name: ${DOCKER_NAME}-scripts
    env_file:
      - .env
    volumes:
      - ./scripts:/app
      - ./.env:/.env
    networks:
      - network

networks:
  network:
    name: ${DOCKER_NAME}-network