FROM public.ecr.aws/sam/build-python3.12

WORKDIR /app

RUN pip install --no-cache-dir --upgrade pip setuptools wheel

COPY be-function-src/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir uvicorn

COPY be-function-src .

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]