FROM public.ecr.aws/sam/build-python3.12

WORKDIR /app

RUN pip install --no-cache-dir --upgrade pip setuptools wheel

COPY be-function-src/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt uvicorn

COPY be-function-src .
COPY static ./static

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]