"""Canonical API route names and path templates."""

API_URL_ROUTES = {
    "upload-public-file": "/public-file",
    "create-article": "/articles",
    "articles-fragment": "/articles-fragment",
    "article-comments-fragment": "/articles/{article_id}/comments-fragment",
    "update-article": "/articles/{article_id}",
    "update-article-status": "/articles/{article_id}/status",
    "update-article-impression": "/articles/{article_id}/impression",
    "create-article-comment": "/articles/{article_id}/comment",
    "update-article-comment": "/articles/{article_id}/comments/{comment_id}",
    "create-contact-message": "/contacts/message",
    "get-article-tag-subscriptions": "/article-tag-subscriptions",
    "create-article-tag-subscription": "/article-tag-subscriptions",
    "delete-article-tag-subscription": "/article-tag-subscriptions/{article_tag_subscription_id}",
    "update-article-tag": "/article-tags/{slug}",
    "get-article-tags": "/article-tags",
    "article-tags-fragment": "/article-tags-fragment",
    "users-fragment": "/users-fragment",
    "update-user-status": "/users/{user_id}/status",
    "update-user-impression": "/users/{user_id}/impression",
    "update-user-activity-settings": "/users/{user_id}/activity-settings",
    "update-user-interests-settings": "/users/{user_id}/interests-settings",
    "update-user": "/users/{user_id}",
    "user-articles-fragment": "/users/{user_id}/articles-fragment",
    "create-dummy-fixtures": "/dummy-fixtures",
    "generate-sitemap": "/generate-sitemap",
    "drop-cdn-cache": "/drop-cdn-cache",
}
