"""Canonical web route names and path templates."""

WEB_URL_ROUTES = {
    "index": "/",
    "new-article": "/articles/new",
    "articles": "/articles",
    "tags": "/tags",
    "article": "/articles/{article_id}",
    "edit-article": "/articles/{article_id}/edit",
    "articles-by-slugs": "/{slugs_path:path}/articles",
    "legacy-posts": "/posts",
    "legacy-singular-articles": "/post",
    "legacy-new-article": "/posts/new",
    "legacy-singular-new-article": "/post/new",
    "legacy-article": "/posts/{article_id}",
    "legacy-singular-article": "/post/{article_id}",
    "legacy-edit-article": "/posts/{article_id}/edit",
    "legacy-singular-edit-article": "/post/{article_id}/edit",
    "legacy-posts-by-slugs": "/{slugs_path:path}/posts",
    "contacts": "/contacts",
    "edit-tag": "/tags/{slug}/edit",
    "users": "/users",
    "users-by-slugs": "/{type}/users",
    "user": "/users/{user_id}",
    "edit-user": "/users/{user_id}/edit",
    "login": "/login",
    "login-callback": "/login-callback",
    "logout": "/logout",
    "logout-callback": "/logout-callback",
    "policy": "/privacy-policy",
    "rules": "/rules",
    "terms": "/terms-of-service",
    "earn": "/earn-with-us",
    "utils": "/utils",
    "user-by-slug": "/{slug}",
    "article-by-slugs": "/{user_slug}/{article_slug}",
}
