"""Canonical API route names and path templates."""

API_URL_ROUTES = {
    "upload-public-file": "/api/public-file",
    "create-article": "/api/articles",
    "articles-fragment": "/api/articles-fragment",
    "article-comments-fragment": "/api/articles/{article_id}/comments-fragment",
    "update-article": "/api/articles/{article_id}",
    "update-article-status": "/api/articles/{article_id}/status",
    "update-article-impression": "/api/articles/{article_id}/impression",
    "create-article-comment": "/api/articles/{article_id}/comment",
    "update-article-comment": "/api/articles/{article_id}/comments/{comment_id}",
    "create-contact-message": "/api/contacts/message",
    "get-article-tag-subscriptions": "/api/article-tag-subscriptions",
    "create-article-tag-subscription": "/api/article-tag-subscriptions",
    "delete-article-tag-subscription": "/api/article-tag-subscriptions/{article_tag_subscription_id}",
    "update-article-tag": "/api/article-tags/{slug}",
    "get-article-tags": "/api/article-tags",
    "users-fragment": "/api/users-fragment",
    "update-user-status": "/api/users/{user_id}/status",
    "update-user-impression": "/api/users/{user_id}/impression",
    "update-user-activity-settings": "/api/users/{user_id}/activity-settings",
    "update-user-interests-settings": "/api/users/{user_id}/interests-settings",
    "update-user": "/api/users/{user_id}",
    "user-articles-fragment": "/api/users/{user_id}/articles-fragment",
    "create-dummy-fixtures": "/api/dummy-fixtures",
    "generate-sitemap": "/api/generate-sitemap",
    "drop-cdn-cache": "/api/drop-cdn-cache",
}
